### ISSUE TITLE
Understanding the code

### ISSUE THREAD

**Issue by dmanion** [jdnichollsc/Ionic-Starter-Template#10]
Hello, I am new to developing angular / ionic and I try to understand how the prepopulated database in your example works. I tried to replicate this in a minimal example, but my database is always empty when I run the code in an android emulator. Your example works in the emulator.

What steps are necessary for a prepopulated database to work?
- adding `cordova-sqlite-ext` via `ionic plugin add link-to-git-repo`
- having the database in folder `\www`
- accessing the database after `device-ready`-event 

Did I miss anything out?

Any help would be much appriciated.

**Comment by jdnichollsc** [comment]
To install all plugins, you need execute the command: `ionic platform add android`
To modify the database **./www/pre.db**, you need use [DB Browser for SQLite](http://sqlitebrowser.org/)

And later you can test on your mobile with the command: `ionic run android`
