### ISSUE TITLE
Sobreescribiendo Variables de Ionic

### ISSUE THREAD

**Issue by stiago2** [jdnichollsc/Ionic-Starter-Template#12]
Buenos dias.
Estoy usando tu plantilla pero tengo un problema.
Necesito sobreescribir los valores de las variables sass de ionic como $dark o $royal, esto lo estoy intentando hacer desde un archivo sass ubicado en la ruta app/sass, es necesario incluirle algun tipo de configuracion extra para que lo detecte?

**Comment by jdnichollsc** [comment]
Hi @stiago2 
You can use the file **./scss/ionic.app.scss** to do that :+1: 

It's neccesary to modify the **./app/index.html** to use the following code:

``` javascript
<!-- IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
  <link href="css/ionic.app.css" rel="stylesheet">
-->
```

Regards, Nicholls
