### ISSUE TITLE
Ionic 2.0 and gulp?

### ISSUE THREAD

**Issue by Shadowstep33** [jdnichollsc/Ionic-Starter-Template#13]
Hey I just updated to Ionic 2.0 and gulp doesn't seem to be rebuilding on file change. Ionic reloads when files change but gulp doesn't log any of the stuff it normally does (scripts built, templates built, etc).

Any idea? I'm a huge noob when it comes to gulp and only finally becoming moderately comfortable with Ionic :(

**Comment by jdnichollsc** [comment]
As I can see you can't use both versions in the same machine because the configuration is different, maybe you can check that in the forum :/

**Comment by jdnichollsc** [comment]
Can you try again please? Check the little changes https://github.com/jdnichollsc/Ionic-Starter-Template/commit/7f231d52819ec062241a31bab36cd64148f8872c
