### ISSUE TITLE
Sass changes but not gulp .scss files again - ionic serve

### ISSUE THREAD

**Issue by vinimendes3** [jdnichollsc/Ionic-Starter-Template#14]
When I change my files (.js, .html), it gulp again these files and show me the change in live preview (ionic serve). But when I change .scss files, it only update the page, but not gulp again my .scss files, forcing me to stop "ionic serve", type "gulp" process, and type "ionic serve" again. But it causes me a lot of time in .scss files changes. How could I fix it?

Thanks in advance!

**Comment by jdnichollsc** [comment]
Can you try using F5 for now? :/ Let me check at night

**Comment by jdnichollsc** [comment]
@vinimendes3 Check please my last commit and let me know :) https://github.com/jdnichollsc/Ionic-Starter-Template/commit/7f231d52819ec062241a31bab36cd64148f8872c
