### ISSUE TITLE
Sqlite database prepopulated on android device

### ISSUE THREAD

**Issue by cerge** [jdnichollsc/Ionic-Starter-Template#16]
Hi, the template is great and it  works fine on browser but I cant check it on my device (moto g) .Basically I need load a old sqlite file (with 4 big tables) and execute some sql queries, but Im not sure how debug it . On a first view it dont load the queries on my device but works fine on chrome browser (with web databases) Please, let me know if you can recommend me some tool or solution so i can check what happens and help on the development of this great project.

**Comment by jdnichollsc** [comment]
Try GapDebug to debug your app https://www.genuitec.com/products/gapdebug/
Regards, Nicholls

**Comment by cerge** [comment]
Thanks Nicholls, All seems works fine now but like the other question, seems it works with webDB in browser and mobile (on this last case, seems it dont load the pre.db file) Probably some issue with the line: if (window.sqlitePlugin !== undefined) {

**Comment by jdnichollsc** [comment]
On mobile works with a [SQLite plugin](https://github.com/litehelpers/cordova-sqlite-ext) instead of WebDB, you can find this plugin into Config.xml file.
And you can edit the pre.db file using http://sqlitebrowser.org/ :)
