### ISSUE TITLE
Starter template for Ionic v2?

### ISSUE THREAD

**Issue by michaeljcoyne** [jdnichollsc/Ionic-Starter-Template#17]
Starter template for Ionic v2?

**Comment by jdnichollsc** [comment]
Hi @michaeljcoyne!

You can use the **[Ionic Super Starter](https://github.com/driftyco/ionic-starter-super)** created by the Ionic team.

Regards, Nicholls

**Comment by michaeljcoyne** [comment]
Thanks but I don't see any SQLite in here which is what I was after.
