### ISSUE TITLE
Failed to load “page” resource: Could not connect to the server (iOS app) 

### ISSUE THREAD

**Issue by vinimendes3** [jdnichollsc/Ionic-Starter-Template#18]
I don't know if this is a problem directly related to this template but I'm having a strange problem with my iOS App.

In my iOS device App, I'm having the following problem after I let my app a few moment in background and return to it:

![screen shot 2017-05-12 at 6 30 58 pm](https://cloud.githubusercontent.com/assets/3437722/26059463/3e3cdbf2-3958-11e7-8176-03cd7d50cb23.png)

This image is from iOS device. I inspected from Safari.

I can use the app normally, and all the screens work well. But if I minimize the app pressing the home button on device, and wait a few moment and try to open again, the screens not load and I have errors similar to the errors of the screenshot. To solve this in the moment, it forces the user to close the app and open again to reload. Why does it happen? How can I solve this?

Thanks.

**Comment by vinimendes3** [comment]
I just solved!!! The problem was because I was using "Cordova WKWebView Engine" as iOS webview, and I don't know why it was causing me this problem. I uninstalled this webview and now it is working normally.

**Comment by jdnichollsc** [comment]
Very odd
