### ISSUE TITLE
Fix Auto reload (watch)

### ISSUE THREAD

**Issue by alsastre** [jdnichollsc/Ionic-Starter-Template#20]
I just started with ionic and first of all I want to thank you for your great template.
I have cloned the last github version and with the lastest version of ionic (3.19.0) the browser (ionic serve) won't update to changes in the app directory.
Investigating the problem I have found a solution here: https://forum.ionicframework.com/t/ionic-cli-doesnt-run-gulp-tasks-on-ionic-serve/49085/26
and it consist on changing the line 34 of the **gulpfile.js** ``gulp.task('serve:before', ['watch']);``
 for ``gulp.task('ionic:watch:before', ['watch'])``
Thank you and great work

**Comment by jdnichollsc** [comment]
Excellent my friend, @alsastre can you create a pull request for this change please?

**Comment by jdnichollsc** [comment]
Thanks!
