### ISSUE TITLE
I cannot Install you template

### ISSUE THREAD

**Issue by Peras795** [jdnichollsc/Ionic-Starter-Template#23]
Hello,

I'm trying to use your awesome template but I find this error on using npm install:

npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The link to that plugin is down and I dont know what to do: I have node-sass 4.9 installed but your templated is still requiring that specific version.

Thanks in advanced,

Alex.

**Comment by jdnichollsc** [comment]
@Peras795 Do you need Ionic 1? If you want you can try the **Ionic Super Starter** with the last version of Ionic https://github.com/ionic-team/starters/tree/master/ionic-angular/official/super
Best regards, Nicholls
