### ISSUE TITLE
Can we use for Ionic 3 version

### ISSUE THREAD

**Issue by sarancruzer** [jdnichollsc/Ionic-Starter-Template#24]
Can we use for Ionic 3 version

**Comment by jdnichollsc** [comment]
No, this is an old template for Ionic 1, you can use the Ionic Super Starter with **Ionic 3** [here](https://github.com/ionic-team/starters/tree/master/ionic-angular/official/super) 👍

**Comment by sarancruzer** [comment]
Ok I agree your point 
Could you pls give me a animation solution like this
[https://gonehybrid.com/how-to-animate-your-ionic-app-with-animate-css-and-nganimate/](here)

**Comment by jdnichollsc** [comment]
Ohh You need to learn about **Angular Animations API**:
- https://angular.io/guide/animations
- https://coursetro.com/posts/code/63/Angular-4-Animation-Tutorial
- https://medium.com/@aleixsuau/angular-animations-bring-life-to-your-apps-ca122e5db647
- https://medium.com/frontend-coach/angular-in-motion-4-approaches-to-animation-1aa7426aae5a
- https://alligator.io/angular/animation-angular/
- https://www.joshmorony.com/using-the-web-animations-api-in-ionic-2/

In the case of **Animate.css**, you can see the following [link](https://github.com/yuyang041060120/ng2-animate)

Regards, Nicholls
