### ISSUE TITLE
Estructura por componentes

### ISSUE THREAD

**Issue by luisestebanveragomez** [jdnichollsc/Ionic-Starter-Template#4]
Hola

Seria genial que la estrucutra trabajara por componentes, con ello al remover uno tan solo es quitar una carpeta ejemplo:

  `home/
   home.sass
  home.tpl.html
home.js`

  `about/
   about.sass
  about.tpl.html
about.js`

Saludos!

**Comment by jdnichollsc** [comment]
Puedes pasarme tu archivo **gulp** como ejemplo para crear esta otra estructura? :dancers:

**Comment by luisestebanveragomez** [comment]
Clara men, he hecho una base con componentes, como es tu correo?
no se como adjuntar archivos desde aqui jajaja

**Comment by jdnichollsc** [comment]
Mi correo es jdnichollsc@hotmail.com
PD: Es la primera vez que copio en español aquí en GitHub...

**Comment by jdnichollsc** [comment]
Como ya Ionic 2 trabaja basado en componentes, ya no veo la necesidad de implementar este fix en este repo con Ionic 1 :) so... caso cerrado! jaja

**Comment by jdnichollsc** [comment]
@kiokotzu llegaste a probar el ciclo de vida de **Ionic 1** con componentes? 😕

**Comment by luisestebanveragomez** [comment]
@jdnichollsc muy poco, fui migrando rapidamente a angular 2 XD

**Comment by jdnichollsc** [comment]
@kiokotzu ahh ya, es que quiero hacer un **migration guide** a la última versión de Ionic con Angular 4, entonces estoy viendo como juntar ambos e ir migrando por partes :)
