### ISSUE TITLE
URL parameters preventing the view to load

### ISSUE THREAD

**Issue by ondeos** [jdnichollsc/Ionic-Starter-Template#6]
Hi there, we are started using your template to build a mobile app. We are having some problem with passing variables on the query string in app.js. It's working fine in ionic blank and Ionic Material projects.

Here is my sample code on app.js

`.state('app.subservice', {
            url: "/subservice/:subserviceId/",
            cache: false,
            views: {
                viewContent: {
                    templateUrl: "templates/subservice.html",
                    controller: 'SubServiceController'
                }
            }
        })`

The problem is when I try to access http://localhost:8100/#/app/subservice/3 or just http://localhost:8100/#/app/subservice/  it redirect back to the default state. But when I removed the "/:subserviceId" and try to access  http://localhost:8100/#/app/subservice/ then it works fine.

I really appreciate your help!

**Comment by jdnichollsc** [comment]
Can you share your example in codepen? :)

See my demos: http://codepen.io/collection/DRzLVL/

You can fork any demo and change the code to reproduce the issue.

Regards, Nicholls

**Comment by jdnichollsc** [comment]
@ondeos Download the template again, you can see a new state using parameters with Angular UI router! :dancers: 

Regards, Nicholls
