### ISSUE TITLE
Two template folders?

### ISSUE THREAD

**Issue by Shadowstep33** [jdnichollsc/Ionic-Starter-Template#7]
Hey man, everything working great so far! Was curious, what is the diifference b/w app/templates and www/templates. Seems app/templates is the rendered template, but www/templates still needs to be populated for a view to work. Any input?

**Comment by Shadowstep33** [comment]
I think I answered my own question: gulp builds www, so when you make a new template in app/templates it actually gets automagically populated to www/templates, I think I just wasn't refreshing my file explorer :)

**Comment by jdnichollsc** [comment]
hahaha yes, gulp is used to reduce the size of your mobile app :+1:
