### ISSUE TITLE
A module out of date?

### ISSUE THREAD

**Issue by Shadowstep33** [jdnichollsc/Ionic-Starter-Template#8]
This happened both times I installed it (on two separate servers): errors about gulp-notify and send-notify.

I cd'd into node_modules/gulp-notify ran npm install and npm update

and same in top lvl ionic template dir.

npm install -g cordova ionic

then 

npm update -g

npm install -g ionic

then I logged in with Ionic

so it's either a module out of date in my -g modules or locally not quite sure. Im also not fully sure which combination of the following worked... sorry :( 

Other than 1 minor other problem, I've hit no problems so far! Great stuff!

**Comment by jdnichollsc** [comment]
But are errors of the modules, It is not a template error :)
